### ISSUE TITLE
Sort out DB Scheme mess

### ISSUE THREAD

**Issue by spinza** [southern-wind/wind#49]
I've reverted 1.2 and my fix for ip unsigned columns.

Want to do the new fix but before I have to revert something again we need to clarify a couple of things:
1. I see in your PR you update the scheme.sql?  Does that need to be updated to be the newest scheme?  Or the starting version?  I assumed the install script updates the db also.
2. I have no idea how to write the update table in the scheme 1.2 to change those ip columns to unsigned int?  I can add a column, not sure how to change one.
3. In your PR you also update the previous schema 's in 1.3 but you only need list the schema's in all.inc and just update the schema version (not list more) in update.php: https://github.com/southern-wind/wind/blob/master/tools/update.php#L22 

Point 3 is my understanding and that is how I tested 1.2.

**Comment by jammin84** [comment]
1 - yes. schema.sql should always be the latest version of the db (ie it is used for fresh installs)
- No the setup does not run update.php see "install/steps/step_dbsetup.php"
- It does however add the sql version during install (hardcoded). 
  - This log should probably move to a "schema.version.data.sql" so that its more obvious and doesn't get forgotten when "schema.sql" is revised.

`
"INSERT INTO`update_log`(version_major, version_minor) VALUES(1,1)"
`

2 - for an example look in "tools/updates/schema-v1.1.inc.php" for "$update->modifyColumn"
- function modifyColumn is found in ""globals/classes/DBDescriptors.inc.php"

3 - you look to be right. all.inc.php is just returning an array. 
- Why do we need to edit 2 files to do this? Seems unnecessary.

This is my overview of the fresh install Vs upgrade. Meaning each schema update requires the following 4 files to be modified. (providing we merge all.inc.php into update.php)
![image](https://cloud.githubusercontent.com/assets/6802951/12737393/0047d59e-c993-11e5-8137-c9adcbef817d.png)

**Comment by spinza** [comment]
So a schema update requires the 4 files above plus all.inc.php.

I will follow that approach for now and we can fix all.inc.php later if needs be.

**Comment by jammin84** [comment]
I'm suggesting we just move the small array data found in "all.inc.php" into the update.php file.

This will make 4 rather than 5 files to edit

But otherwise. yes.

**Comment by jammin84** [comment]
@spinza now that it is "Defined", I take it that you will be performing the required update / amalgamation to 1.2?

**Comment by spinza** [comment]
@jammin84 yeah, have been busy the last couple of days.  Will get to it in the next day or two.

**Comment by jammin84** [comment]
no worries :smiley:

**Comment by spinza** [comment]
Schema version for install could just be in the schema.sql?  Why separate it?

**Comment by spinza** [comment]
Schema 1.1 is also wrong as it uses modify column incorrectly.

**Comment by jammin84** [comment]
The reason I thought to separate it was if someone did a db structure dump that the log line would get lost / forgotten .... Otherwise yes, it could be included.

**Comment by spinza** [comment]
It should show up in the diff when you update the schema.sql. 

Maybe we should document schema updates in a schema.md per this discussion.  And have comments in the relevant code files referencing that?

**Comment by jammin84** [comment]
perhaps we just add a github wiki page about it and any other code can just reference that.

ie. a reference to the wiki comment in update.php and another in the install/step ??

**Comment by spinza** [comment]
That could also work, but a docs folder in the repo is so much more portable.  Github wiki is not part of the repo right?

**Comment by jammin84** [comment]
Fair point. Agreed.

**Comment by jammin84** [comment]
I can see that issue 54 has been created to track the docs folder.

Is there anything else required for this issue to be closed?

**Comment by spinza** [comment]
No.  Closing.
